### ISSUE TITLE
Gatsby can't find the plugin

### ISSUE THREAD

**Issue by pepibumur** [ifiokjr/gatsby-plugin-next-seo#12]
## Description
After following the setup instructions, if I try to run the Gatsby website with `yarn develop` Gatsby throws the following error:

<img width="862" alt="image" src="https://user-images.githubusercontent.com/663605/73246711-9732ea00-41af-11ea-9cdc-9c8686ba7aa3.png">

I looked at the `yarn.lock` file and it's pointing to the version 1.4.0. Moreover, the `gatsby-plugin-next-seo` exists under `node_modules` and it seems to have the right content.

## Checklist

- [x] I have read the [**contributing**](https://github.com/ifiokjr/gatsby-plugin-next-seo/blob/master/CONTRIBUTING.md) document.

**Comment by pepibumur** [comment]
Weird. I removed `node_modules`, ran `yarn install`, and upgraded the packages and it started working. Ignore this.

**Comment by mittnavnermike** [comment]
I am seeing the same error when trying to build with gatsby cloud. Clearing the cache on gatsby cloud does not have an effect. Funnily enough it works fine locally, and also builds on Netlify works 🤷‍♂ Any ideas?

**Comment by ifiokjr** [comment]
@mittnavnermike I didn't see this as it was added to a closed issue. Are you still having the problem?

**Comment by adonig** [comment]
@ifiokjr I'm currently experiencing this relatively similar problem:

`Unable to find plugin "[redacted]/node_modules/gatsby-plugin-next-seo". Perhaps you need to install its package?`

I first tried the typical stuff like `gatsby clean` and `rm -rf node_modules` and `rm yarn.lock` etc. and even switching to npm instead of yarn, but it didn't help. Thereafter I thought that it maybe has something to do with using `gatsby-plugin-ts-config`. Now I found this issue. Is there any known workaround to make gatsby find gatsby-plugin-next-seo?

**Comment by adonig** [comment]
@ifiokjr  I found what is causing the issue. I decided to clone gatsby-plugin-next-seo into the plugins folder and use it as a local plugin. I ran `yarn install` and it complained about `pptr-testing-library@0.6.0` being incompatible with node 14.8.0 so I went with `lts/*` in my .nvmrc and was able to build gatsby-plugin-next-seo. Interestingly gatsby still didn't find it, but this time tried the plugin folder `Unable to find plugin "[redacted]/plugins/gatsby-plugin-next-seo"`. So I did more research and found out [gatsby doesn't support plugins not having index.js at the top-level](https://github.com/gatsbyjs/gatsby/issues/14068). So I took a quick shot [inspired by this commit](https://github.com/weirdpattern/gatsby-remark-series/pull/3/commits/62caa3a808dc78b823a34fc06360cb5cc2760b07) and changed the main to index.js and the babel src --out-dir to . in package.json and ran yarn build. Thereafter I was able to run gatsby develop without problems. It's not very clean because it pollutes the plugin top-level but it's a workaround. So maybe you guys have to find a clean solution to be compatible with gatsby requiring index.js at the plugin top-level.
