### ISSUE TITLE
languageAlternate not outputting to source code

### ISSUE THREAD

**Issue by shanejones** [ifiokjr/gatsby-plugin-next-seo#16]
I've tried to implement the hreflang tags using the following code.

```
<GatsbySeo
  title={pageTitle}
  description={metaDescription}
  languageAlternate={
    ({
      hrefLang: "x-default",
      href: "https://domain.com/",
    },
    {
      hrefLang: "en",
      href: "https://domain.com/",
    },
    {
      hrefLang: "no",
      href: "https://domain.com/no/",
    })
  }
  openGraph={{
    title: pageTitle,
    description: metaDescription,
    images: [
      {
        url: "https://domain.com/domain-facebook.jpg",
        width: 1200,
        height: 630,
        alt: "Site Name",
      },
    ],
  }}
/>
```

However, this does not output on the frontend of the site. I've also tested this with 1 languageAlternate as per your documentation and that also does not output at all anywhere in the source code.

I'm currently using Gatsby 2.19.25 and I get the same results using `gatsby build` and `gatsby develop`

**Comment by Suganthan-Mohanadasan** [comment]
Interested as well.

**Comment by ifiokjr** [comment]
Without testing it looks like you're using wrapping the `languageAlternate` in brackets rather than as an array with square brackets.

**Comment by shanejones** [comment]
Hey @ifiokjr 

I replaced with square brackets and still nothing outputs. As mentioned above too I replaced with a single item using the exact syntax as the documentation and nothing is outputting.

**Comment by ifiokjr** [comment]
Okay, I'll take a look later today. I was responding from my phone so couldn't check it out.

**Comment by ifiokjr** [comment]
Ahhh turns out the docs are wrong. The property name is `languageAlternates` and it takes an array. 

There's an example in the tests.

https://github.com/ifiokjr/gatsby-plugin-next-seo/blob/f01ca33d65c4db578252f0e1b4afeccb3360ddfa/src/meta/__tests__/base-seo.test.tsx#L18-L27

And here's the snapshot produced. 

https://github.com/ifiokjr/gatsby-plugin-next-seo/blob/f01ca33d65c4db578252f0e1b4afeccb3360ddfa/src/meta/__tests__/__snapshots__/base-seo.test.tsx.snap#L600-L613

I'll close this once I've updated the docs. It doesn't really make sense to have a single property option as the docs currently state.

**Comment by ifiokjr** [comment]
Did that fix it for you?
