### ISSUE TITLE
Issue with Gatsby 3.0

### ISSUE THREAD

**Issue by emt-mocha** [ifiokjr/gatsby-plugin-next-seo#40]
I found some warning issued during the installation over the new Gatsby 3.0 today. The npm installer is issuing compatibility error as below: 
_

> λ npm install --save gatsby-plugin-next-seo react-helmet-async
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: dad-gatsby-cloud-web-site@1.0.0
> npm ERR! Found: gatsby@3.0.1
> npm ERR! node_modules/gatsby
> npm ERR!   gatsby@"^3.0.1" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer gatsby@"^2" from gatsby-plugin-next-seo@1.7.0
> npm ERR! node_modules/gatsby-plugin-next-seo
> npm ERR!   gatsby-plugin-next-seo@"*" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR! See C:\Users\ajaya\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\ajaya\AppData\Local\npm-cache\_logs\2021-03-04T09_31_53_780Z-debug.log

_

Somehow I did force install the package and found out that the following code at below is no longer working. 

`<GatsbySeo
      title='Simple Usage Example'
      description='A short description goes here.'
    />`

Thank you,

**Comment by AndriiChubariev** [comment]
Yes, please!

**Comment by llbbl** [comment]
FYI ; I am not sure if there is an issue with this plugin also .... 

I am in deep in the internals trying to fix this using custom SEO component because the problem ->

Facebook social images not working because Gatsby injects css above the <meta og*> tags. I have to figure out how to pull the <link css> tag out of the array and force it out below the og tags. Facebook only parses the first 50kb of headers and this css is always more than that even thou its compiled/minified. 

throwing this out there if anyone wants to help with that LMK

**Comment by jdortegar** [comment]
Same issue here!

**Comment by shi-rudo** [comment]
same here!

**Comment by TheOneAndOnlyGarcia** [comment]
please!

**Comment by emt-mocha** [comment]
Hi is there any alternatives apart from this plugin? It seems the maintainer is no longer care about the bug reports. This PLUGIN IS DEATH!

**Comment by gadiel** [comment]
Gatsby 3 support would be amazing!

**Comment by sweethuman** [comment]
Same here!

**Comment by sweethuman** [comment]
Does anyone know feature wise what's broken when using Gatsby 3?
